### ISSUE TITLE
Weird addition - output character distribution probably not inform.

### ISSUE THREAD

**Issue by divVerent** [paulgreg/UniquePasswordBuilder#17]
https://github.com/paulgreg/UniquePasswordBuilder/blob/67fc98394e6c7ce33bb4b3e87512e1b213bec632/src/passwordgeneration.js#L11

Why this weird addition? The result, asuming the inputs go from 0 to 255, will have a triangle probability distribution. You then are taking the mod with availableCharacters.length.

I think the intent is making the distribution more uniform, but byte1 * 256 + byte2 would be actually uniform at 16 bits and thus a lot better.

Probably a minor issue and not relevant in practice, and not worth an incompatible change (except when adding a new hash type and fixing this only for that one). Can you maybe just add a comment explaining how high the entropy per output character is (in bits) given this distribution?

**Comment by paulgreg** [comment]
Here the PR including that comment : https://github.com/paulgreg/UniquePasswordBuilder/pull/18
What do you think ?
